<?php

use Drupal\simple_conreg\Member;
use Drupal\simple_conreg\SimpleConregConfig;
use Drupal\conreg_zambia\Zambia;
use Drupal\conreg_zambia\ZambiaUser;

/*
 * Implement hook_convention_member_updated()
 *
 * Called when member changes.
 * Check if member on Zambia. If so, push update to Zambia member record.
 * If not, check if relevant options checked, and if create Zambia invite.
 *
 * We only push to Zambia on update.
 */

function conreg_zambia_convention_member_updated(Member $member)
{
  // First, make sure member is paid and approved, and not deleted.
  if (!$member->is_paid || !$member->is_approved || $member->is_deleted) {
    return;
  }

  // Next, check at least one of the expected member options is selected for the member.
  $zambia = new Zambia(SimpleConregConfig::getConfig($member->eid));
  $optionFields =  $zambia->config->get('zambia.option_fields');

  $match = FALSE;
  foreach ($optionFields as $optId => $optVal) {
    if ($optVal) {
      if (isset($member->options[$optId]) && $member->options[$optId]->isSelected) {
        $match = TRUE;
      }
    }
  }
  // If option match found, proceed to update or add member.
  if ($match) {
    $user = new ZambiaUser($zambia);
    if ($user->load($member->mid)) {
      // Member already on Zambia. Just update details.
      $user->save($member, false);
    }
    else {
      // Save new user.
      $user->save($member, false);
      // Send email to user.
      $zambia->sendInviteEmail($user);
    }
  }


}
